name: Docker Publish Backend

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v34e1148

      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@ca052bb
        with:
          context: .
          file: LootTradeApiCS/Dockerfile   # or LootTradeApiCS/Dockerfile if not root
          push: true
          tags: |
            laurensdegrootfontys/loottrade-backend:latest
            laurensdegrootfontys/loottrade-backend:${{ github.sha }}
